// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          pgtype.UUID
	Email       string
	Phone       string
	FirstName   string
	LastName    string
	Username    string
	PasswordHsh string
	Salt        string
	AvatarUrl   pgtype.Text
	Bio         pgtype.Text
	IsActive    bool
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	LastLoginAt pgtype.Timestamptz
}
