// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

type Querier interface {
	CheckUserExist(ctx context.Context, arg CheckUserExistParams) (bool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
}

var _ Querier = (*Queries)(nil)
