// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExist = `-- name: CheckUserExist :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      users
    WHERE
      email = $1
      or username = $2
      or phone = $3
  )
`

type CheckUserExistParams struct {
	Email    string
	Username string
	Phone    string
}

func (q *Queries) CheckUserExist(ctx context.Context, arg CheckUserExistParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExist, arg.Email, arg.Username, arg.Phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (
    username,
    email,
    password_hsh,
    salt,
    phone,
    first_name,
    last_name,
    bio,
    avatar_url
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
  id,
  username,
  avatar_url
`

type CreateUserParams struct {
	Username    string
	Email       string
	PasswordHsh string
	Salt        string
	Phone       string
	FirstName   string
	LastName    string
	Bio         pgtype.Text
	AvatarUrl   pgtype.Text
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Username  string
	AvatarUrl pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHsh,
		arg.Salt,
		arg.Phone,
		arg.FirstName,
		arg.LastName,
		arg.Bio,
		arg.AvatarUrl,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username, &i.AvatarUrl)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id,
  username,
  avatar_url,
  password_hsh,
  salt
FROM
  users
WHERE
  email = $1
`

type GetUserByEmailRow struct {
	ID          pgtype.UUID
	Username    string
	AvatarUrl   pgtype.Text
	PasswordHsh string
	Salt        string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.PasswordHsh,
		&i.Salt,
	)
	return i, err
}
